module.exports = function (Pessoa) {

    Pessoa.beforeCreate = function (next, data) {
        data.cadastro = new Date();
        next();
    };







    var teste = {/*[Function: ModelConstructor]*/
        setMaxListeners: null /*[Function]*/,
        emit: null /*[Function]*/,
        addListener: null /*[Function]*/,
        on: null /*[Function]*/,
        once: null /*[Function]*/,
        removeListener: null /*[Function]*/,
        removeAllListeners: null /*[Function]*/,
        listeners: null /*[Function]*/,
        super_:
                {/*[Function: ModelConstructor]*/
                    setMaxListeners: null /*[Function]*/,
                    emit: null /*[Function]*/,
                    addListener: null /*[Function]*/,
                    on: null /*[Function]*/,
                    once: null /*[Function]*/,
                    removeListener: null /*[Function]*/,
                    removeAllListeners: null /*[Function]*/,
                    listeners: null /*[Function]*/,
                    super_:
                            {/*[Function: ModelConstructor]*/
                                setMaxListeners: null /*[Function]*/,
                                emit: null /*[Function]*/,
                                addListener: null /*[Function]*/,
                                on: null /*[Function]*/,
                                once: null /*[Function]*/,
                                removeListener: null /*[Function]*/,
                                removeAllListeners: null /*[Function]*/,
                                listeners: null /*[Function]*/,
                                super_: [Object],
                                defineProperty: null /*[Function]*/,
                                getPropertyType: null /*[Function]*/,
                                isHiddenProperty: null /*[Function]*/,
                                mixin: null /*[Function]*/,
                                getDataSource: null /*[Function]*/,
                                afterInitialize: null,
                                beforeValidate: null,
                                afterValidate: null,
                                beforeSave: null,
                                afterSave: null,
                                beforeCreate: null,
                                afterCreate: null,
                                beforeUpdate: null,
                                afterUpdate: null,
                                beforeDestroy: null,
                                afterDestroy: null,
                                validatesPresenceOf: null /*[Function]*/,
                                validatesAbsenceOf: null /*[Function]*/,
                                validatesLengthOf: null /*[Function]*/,
                                validatesNumericalityOf: null /*[Function]*/,
                                validatesInclusionOf: null /*[Function]*/,
                                validatesExclusionOf: null /*[Function]*/,
                                validatesFormatOf: null /*[Function]*/,
                                validate: null /*[Function]*/,
                                validateAsync: null /*[Function]*/,
                                validatesUniquenessOf: null /*[Function]*/,
                                getter: {},
                                setter: {},
                                definition: [Object],
                                settings: [Object],
                                forEachProperty: null /*[Function]*/,
                                attachTo: null /*[Function]*/,
                                extend: null /*[Function]*/,
                                registerProperty: null /*[Function]*/,
                                setup: null /*[Function]*/,
                                _ACL: null/*[Function: getACL]*/,
                                checkAccess: null /*[Function]*/,
                                _getAccessTypeForMethod: null /*[Function]*/,
                                getApp: null /*[Function]*/,
                                remoteMethod: null /*[Function]*/,
                                belongsToRemoting: null /*[Function]*/,
                                hasOneRemoting: null /*[Function]*/,
                                hasManyRemoting: null /*[Function]*/,
                                scopeRemoting: null /*[Function]*/,
                                nestRemoting: null /*[Function]*/,
                                sharedClass: [Object],
                                sharedCtor: [Object],
                                beforeRemote: null /*[Function]*/,
                                afterRemote: null /*[Function]*/},
                    defineProperty: null /*[Function]*/,
                    getPropertyType: null /*[Function]*/,
                    isHiddenProperty: null /*[Function]*/,
                    mixin: null /*[Function]*/,
                    getDataSource: null /*[Function]*/,
                    afterInitialize: null,
                    beforeValidate: null,
                    afterValidate: null,
                    beforeSave: null,
                    afterSave: null,
                    beforeCreate: null,
                    afterCreate: null,
                    beforeUpdate: null,
                    afterUpdate: null,
                    beforeDestroy: null,
                    afterDestroy: null,
                    validatesPresenceOf: null /*[Function]*/,
                    validatesAbsenceOf: null /*[Function]*/,
                    validatesLengthOf: null /*[Function]*/,
                    validatesNumericalityOf: null /*[Function]*/,
                    validatesInclusionOf: null /*[Function]*/,
                    validatesExclusionOf: null /*[Function]*/,
                    validatesFormatOf: null /*[Function]*/,
                    validate: null /*[Function]*/,
                    validateAsync: null /*[Function]*/,
                    validatesUniquenessOf: null /*[Function]*/,
                    getter: {},
                    setter: {},
                    definition:
                            {modelBuilder: [Object],
                                name: 'PersistedModel',
                                rawProperties: [Object],
                                settings: [Object],
                                relations: [],
                                properties: [Object],
                                _ids: [Object]},
                    settings: {strict: false},
                    forEachProperty: null /*[Function]*/,
                    attachTo: null /*[Function]*/,
                    extend: null /*[Function]*/,
                    registerProperty: null /*[Function]*/,
                    setup: null /*[Function: setupPersistedModel]*/,
                    _ACL: null /*[Function: getACL]*/,
                    checkAccess: null /*[Function]*/,
                    _getAccessTypeForMethod: null /*[Function]*/,
                    getApp: null /*[Function]*/,
                    remoteMethod: null /*[Function]*/,
                    belongsToRemoting: null /*[Function]*/,
                    hasOneRemoting: null /*[Function]*/,
                    hasManyRemoting: null /*[Function]*/,
                    scopeRemoting: null /*[Function]*/,
                    nestRemoting: null /*[Function]*/,
                    sharedClass:
                            {name: 'PersistedModel',
                                ctor: null /*[Circular]*/,
                                _methods: null /*[Object]*/,
                                _resolvers: null /*[Object]*/,
                                http: null /*[Object]*/,
                                sharedCtor: null /*[Object]*/},
                    sharedCtor: null /*{ [Function] accepts: [Object], http: [Object], returns: [Object] }*/,
                    beforeRemote: null /*[Function]*/,
                    afterRemote: null /*[Function]*/,
                    create: null /*{ [Function] _delegate: true }*/,
                    updateOrCreate: null /*{ [Function: upsert] _delegate: true }*/,
                    upsert: null /*{ [Function: upsert] _delegate: true }*/,
                    findOrCreate: null /*{ [Function: findOrCreate] _delegate: true }*/,
                    exists: null /*{ [Function: exists] _delegate: true }*/,
                    findById: null /*{ [Function: find] _delegate: true }*/,
                    find: null /*{ [Function: find] _delegate: true }*/,
                    findOne: null /*{ [Function: findOne] _delegate: true }*/,
                    destroyAll: null /*{ [Function: destroyAll] _delegate: true }*/,
                    deleteAll: null /*{ [Function: destroyAll] _delegate: true }*/,
                    remove: null /*{ [Function: destroyAll] _delegate: true }*/,
                    updateAll: null /*{ [Function: updateAll] _delegate: true }*/,
                    update: null /*{ [Function: updateAll] _delegate: true }*/,
                    destroyById: null /*{ [Function: deleteById] _delegate: true }*/,
                    deleteById: null /*{ [Function: deleteById] _delegate: true }*/,
                    removeById: null /*{ [Function: deleteById] _delegate: true }*/,
                    count: null /*{ null [Function] _delegate: true }*/,
                    getIdName: null /*[Function]*/,
                    setupRemoting: null /*[Function]*/,
                    diff: null /*[Function]*/,
                    changes: null /*[Function]*/,
                    checkpoint: null /*[Function]*/,
                    currentCheckpoint: null /*[Function]*/,
                    replicate: null /*[Function]*/,
                    createUpdates: null /*[Function]*/,
                    bulkUpdate: null /*[Function]*/,
                    getChangeModel: null /*[Function]*/,
                    getSourceId: null /*[Function]*/,
                    enableChangeTracking: null /*[Function]*/,
                    _defineChangeModel: null /*[Function]*/,
                    rectifyAllChanges: null /*[Function]*/,
                    handleChangeError: null /*[Function]*/,
                    rectifyChange: null /*[Function]*/,
                    autoAttach: 'db'},
        defineProperty: null /*[Function]*/,
        getPropertyType: null /*[Function]*/,
        isHiddenProperty: null /*[Function]*/,
        mixin: null /*[Function]*/,
        getDataSource: null /*[Function]*/,
        afterInitialize: null,
        beforeValidate: null,
        afterValidate: null,
        beforeSave: null,
        afterSave: null,
        beforeCreate: null,
        afterCreate: null,
        beforeUpdate: null,
        afterUpdate: null,
        beforeDestroy: null,
        afterDestroy: null,
        validatesPresenceOf: null /*[Function]*/,
        validatesAbsenceOf: null /*[Function]*/,
        validatesLengthOf: null /*[Function]*/,
        validatesNumericalityOf: null /*[Function]*/,
        validatesInclusionOf: null /*[Function]*/,
        validatesExclusionOf: null /*[Function]*/,
        validatesFormatOf: null /*[Function]*/,
        validate: null /*[Function]*/,
        validateAsync: null /*[Function]*/,
        validatesUniquenessOf: null /*[Function]*/,
        getter: {},
        setter: {},
        definition:
                {modelBuilder:
                            {models: [Object],
                                definitions: [Object],
                                mixins: [Object],
                                defaultModelBaseClass: [Object],
                                _nameCount: 5},
                    name: 'Pessoa',
                    rawProperties:
                            {cadastro: [Object],
                                nome: [Object],
                                nascimento: [Object],
                                id: [Object]},
                    settings:
                            {strict: false,
                                plural: 'Pessoas',
                                base: 'PersistedModel',
                                validations: [],
                                relations: {},
                                acls: [],
                                methods: []},
                    relations: [],
                    properties:
                            {cadastro: [Object],
                                nome: [Object],
                                nascimento: [Object],
                                id: [Object]},
                    _ids: [[Object]]},
        settings:
                {strict: false,
                    plural: 'Pessoas',
                    base: 'PersistedModel',
                    validations: [],
                    relations: {},
                    acls: [],
                    methods: []},
        forEachProperty: null /*[Function]*/,
        attachTo: null /*[Function]*/,
        extend: null /*[Function]*/,
        registerProperty: null /*[Function]*/,
        setup: null /*[Function: setupPersistedModel]*/,
        _ACL: null /*[Function: getACL]*/,
        checkAccess: null /*[Function]*/,
        _getAccessTypeForMethod: null /*[Function]*/,
        getApp: null /*[Function]*/,
        remoteMethod: null /*[Function]*/,
        belongsToRemoting: null /*[Function]*/,
        hasOneRemoting: null /*[Function]*/,
        hasManyRemoting: null /*[Function]*/,
        scopeRemoting: null /*[Function]*/,
        nestRemoting: null /*[Function]*/,
        sharedClass:
                {name: 'Pessoa',
                    ctor: null /*[Circular]*/,
                    _methods:
                            [[Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object],
                                [Object]],
                    _resolvers: null /*[ [Function: resolver] ]*/,
                    http: {path: '/Pessoas'},
                    sharedCtor:
                            {fn: [Object],
                                name: 'sharedCtor',
                                aliases: [],
                                isStatic: false,
                                accepts: [Object],
                                returns: [Object],
                                description: undefined,
                                http: [Object],
                                rest: {},
                                shared: true,
                                sharedClass: null /*[Circular]*/,
                                ctor: null /*[Circular]*/,
                                sharedCtor: undefined,
                                isSharedCtor: true,
                                stringName: 'Pessoa.prototype.sharedCtor'}},
        sharedCtor: null /*
         { null [Function]
         accepts: [ [Object] ],
         http: [ [Object] ],
         returns: { root: true } }*/,
        beforeRemote: null /*[Function]*/,
        afterRemote: null /*[Function]*/,
        create: null /*{ null [Function] _delegate: true }*/,
        updateOrCreate: null /*{ [Function: upsert] _delegate: true }*/,
        upsert: null /*{ [Function: upsert] _delegate: true }*/,
        findOrCreate: null /*{ [Function: findOrCreate] _delegate: true }*/,
        exists: null /*{ [Function: exists] _delegate: true }*/,
        findById: null /*{ [Function: find] _delegate: true }*/,
        find: null /*{ [Function: find] _delegate: true }*/,
        findOne: null /*{ [Function: findOne] _delegate: true }*/,
        destroyAll: null /*{ [Function: destroyAll] _delegate: true }*/,
        deleteAll: null /*{ [Function: destroyAll] _delegate: true }*/,
        remove: null /*{ [Function: destroyAll] _delegate: true }*/,
        updateAll: null /*{ [Function: updateAll] _delegate: true }*/,
        update: null /*{ [Function: updateAll] _delegate: true }*/,
        destroyById: null /*{ [Function: deleteById] _delegate: true }*/,
        deleteById: null /*{ [Function: deleteById] _delegate: true }*/,
        removeById: null /*{ [Function: deleteById] _delegate: true }*/,
        count: null /*{ null [Function] _delegate: true }*/,
        getIdName: null /*[Function]*/,
        setupRemoting: null /*[Function]*/,
        diff: null /*[Function]*/,
        changes: null /*[Function]*/,
        checkpoint: null /*[Function]*/,
        currentCheckpoint: null /*[Function]*/,
        replicate: null /*[Function]*/,
        createUpdates: null /*[Function]*/,
        bulkUpdate: null /*[Function]*/,
        getChangeModel: null /*[Function]*/,
        getSourceId: null /*[Function]*/,
        enableChangeTracking: null /*[Function]*/,
        _defineChangeModel: null /*[Function]*/,
        rectifyAllChanges: null /*[Function]*/,
        handleChangeError: null /*[Function]*/,
        rectifyChange: null /*[Function]*/,
        autoAttach: 'db'
    };

};
